spring:
  application:
    name: spring-config-server
  cloud:
    config:
      server:
        git:
          uri: http://git.oschina.net/didispace/SpringCloud-Learning/
          search-paths: spring_cloud_in_action/config-repo
          username: username
          password: password
server:
  port: 8012
